api-version: 1.20
main: com.bubbaj2016.darkmc.Plugin
name: darkmc
version: 1.0
commands:
    helloWorld:
        description: Hello, World!
        usage: /<command>
    KeyCommand:
        description: gives key
        usage: /<command>
    LocWandCommand:
        description: gives Loc Wand
        usage: /<command>
    RemoveBlocksCommand:
        description: gives Loc Wand
        usage: /<command>
    Money:
        description: gets money balance
        usage: /<command>
    getJobs:
        description: gets job list
        usage: /<command>
    shop:
        description: opens shop
        usage: /<command>
    
    